### ISSUE TITLE
Sinatra: first load of site causes" NameError - uninitialized constant ActiveSupport"

### ISSUE THREAD

**Issue by soumyaray** [twitter/secureheaders#262]
Im using SecureHeaders on Sinatra, and the first time the site is loaded, it crashes with a "NameError - uninitialized constant ActiveSupport" (stack trace below).  I'm using a classic style Sinatra app (for demo purposes). I find that the crash is caused once `use SecureHeaders::Middleware` is put into the code, regardless of whether a config has been defined.

```
2016-06-02 15:23:08 - NameError - uninitialized constant ActiveSupport:
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/temple-0.7.7/lib/temple/templates/rails.rb:17:in `register_as'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/temple-0.7.7/lib/temple/mixins/template.rb:23:in `create'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/temple-0.7.7/lib/temple/templates.rb:8:in `method_missing'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/slim-3.0.7/lib/slim/template.rb:9:in `<module:Slim>'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/slim-3.0.7/lib/slim/template.rb:1:in `<top (required)>'
	/Users/soumyaray/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/Users/soumyaray/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/slim-3.0.7/lib/slim.rb:13:in `<top (required)>'
	/Users/soumyaray/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	/Users/soumyaray/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	/Users/soumyaray/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt/mapping.rb:236:in `block in lazy_load'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt/mapping.rb:234:in `each'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt/mapping.rb:234:in `lazy_load'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt/mapping.rb:214:in `lookup'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt/mapping.rb:152:in `[]'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt.rb:48:in `[]'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:842:in `block in compile_template'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt.rb:104:in `block in fetch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt.rb:103:in `fetch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/tilt-2.0.4/lib/tilt.rb:103:in `fetch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:841:in `compile_template'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:822:in `render'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:744:in `slim'
	app.rb:6:in `block in <main>'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/secure_headers-3.3.2/lib/secure_headers/middleware.rb:12:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `call'
	/Users/soumyaray/.rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
```

**Comment by soumyaray** [comment]
I should add that everything works fine from the second load of the site onwards. Also, the app code is available at: https://github.com/ISS-Security/demo-xss/blob/master/app.rb

**Comment by jacobbednarz** [comment]
I _think_ this is a load order issue since the secure headers middleware is loaded so early on...bit odd about it working the second time though. I done some work on load order with rails a while back for another issue which I'll dig up and see if it's any benefit to you and your app.

**Comment by soumyaray** [comment]
thanks! and to clarify, from the second load onwards it works completely: it doesn't crash and it catches everything.

**Comment by soumyaray** [comment]
Super sorry to waste your time -- I simply forgot to `require 'slim'` in my code. I still don't know why the temple gem borked only when SecureHeaders was used. But in any case, it works fine now that I've required slim.  Thanks for your fine gem!
